name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: Create .env
        run: |
          echo "VITE_EMAIL=${{ secrets.VITE_EMAIL }}" >> .env.production
          echo "VITE_PHONE=${{ secrets.VITE_PHONE }}" >> .env.production

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm run build
          touch dist/.nojekyll

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
