name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: Create .env file
        run: |
          echo "VITE_EMAIL=${{ secrets.VITE_EMAIL }}" >> .env
          echo "VITE_PHONE=${{ secrets.VITE_PHONE }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: dist
          github_token: ${{ secrets.GH_TOKEN }}
